# k8s/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service # This name will be used to access the frontend from outside
spec:
  selector:
    app: frontend # Selects pods with the label 'app: frontend' (from frontend-deployment.yaml)
  ports:
    - protocol: TCP
      port: 80 # The port that this Kubernetes Service exposes
      targetPort: 80 # The port on the container that the service targets (Nginx's port)
  type: NodePort # This type makes the service accessible from outside the cluster on a specific port on each node
